# Generated by Django 4.2.5 on 2023-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Fantansy', 'Fantansy'), ('Romance', 'Romanace')], default='Comedy', max_length=100, null='CM'),
        ),
    ]
