# Generated by Django 4.2.6 on 2023-10-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0014_remove_comment_parent_comment_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recomment',
            name='content',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recomment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
